version: "2"

services:
  skyline:
    container_name: skyline
    env_file: .env
    ports:
      - "8998:3000"
    image: node:16
    restart: unless-stopped
    working_dir: /usr/skyline/server
    volumes:
      - .:/usr/skyline/server
    command: yarn prod
