export type tba_team = {
	address: null;
	city: string;
	country: string;
	gmaps_place_id: null;
	gmaps_url: null;
	key: string;
	lat: null;
	lng: null;
	location_name: null;
	motto: null;
	name: string;
	nickname: string;
	postal_code: string;
	rookie_year: number;
	school_name: string;
	state_prov: string;
	team_number: number;
	website: string;
};
