name: Deploy Skyline

on:
  push:
    branches:
      - main

jobs:
  deploy-us:
    name: Deploy US
    runs-on: self-hosted
    environment: production-us

    steps:
      - run: echo ${{ secrets.KEY }} | sudo -S rm -rf /pools/pool-1/storagesmash/gh-runners/skyline-server/_work/skyline/skyline/node_modules || true
      - run: echo ${{ secrets.KEY }} | sudo -S rm -rf /pools/pool-1/storagesmash/gh-runners/skyline-server/_work/skyline/skyline/generated || true
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - uses: SpicyPizza/create-envfile@v1
        with:
          envkey_PORT: ${{ secrets.PORT }}
          file_name: .env
      - run: docker-compose up -d --force-recreate